### ISSUE TITLE
`block in ': undefined method `humanize' for \"write_fragment\":String (NoMethodError) upon require

### ISSUE THREAD

**Issue by mensfeld** [pathouse/logjoy#1]
Hey,

When I require logjoy I get following error:

```
bundler: failed to load command: /app/bin/probe.rb (/app/bin/probe.rb)
/app/vendor/bundle/ruby/2.7.0/gems/actionpack-6.1.4.1/lib/action_controller/log_subscriber.rb:69:in `block in ': undefined method `humanize' for \"write_fragment\":String (NoMethodError)
\tfrom /app/vendor/bundle/ruby/2.7.0/gems/actionpack-6.1.4.1/lib/action_controller/log_subscriber.rb:64:in `each'
\tfrom /app/vendor/bundle/ruby/2.7.0/gems/actionpack-6.1.4.1/lib/action_controller/log_subscriber.rb:64:in `'
\tfrom /app/vendor/bundle/ruby/2.7.0/gems/actionpack-6.1.4.1/lib/action_controller/log_subscriber.rb:4:in `'
\tfrom /app/vendor/bundle/ruby/2.7.0/gems/actionpack-6.1.4.1/lib/action_controller/log_subscriber.rb:3:in `'
\tfrom /app/vendor/bundle/ruby/2.7.0/gems/logjoy-0.3.1/lib/logjoy.rb:4:in `require'
\tfrom /app/vendor/bundle/ruby/2.7.0/gems/logjoy-0.3.1/lib/logjoy.rb:4:in `'
```

**Comment by pathouse** [comment]
hey @mensfeld can you share some more info about where you are calling require? not sure how to replicate this issue on my end

**Comment by mensfeld** [comment]
Name this file something like `repro.rb`

```ruby
require 'bundler/inline'

gemfile do
  source 'https://rubygems.org'
  gem 'logjoy'
end

require 'logjoy'

```

and then just: `ruby repro.rb`

**Comment by pathouse** [comment]
ah I see thanks @mensfeld - this gem is not going to work outside of a Rails app - I can update the README to make that more explicit

**Comment by mensfeld** [comment]
You've added Rails as deps; https://github.com/pathouse/logjoy/blob/main/logjoy.gemspec#L27 thus it should require it as things are being resolved.

**Comment by pathouse** [comment]
I was able to resolve this by removing an extra require I had in there - should be able to run your example now w/ v. 0.3.3 

thought TBH this is my first time trying to build a rails extension like this so I'm not entirely clear on exactly when I need to use require and when I don't - thanks for bearing with me here

**Comment by mensfeld** [comment]
:) thank you!

FYI if you are building things that you would like to work with or without Rails, you could use a conditional railtie like so:

https://github.com/karafka/karafka/blob/eb638b913f791adb2918aa8031daa13522cd09eb/lib/karafka/railtie.rb

**Comment by mensfeld** [comment]
FYI I'm still getting it in 0.3.3 :(

**Comment by pathouse** [comment]
ah you are right my apologies - I had to change up the order of require statements to get the active support string extensions loaded first - pushed 0.3.4 with that change

**Comment by mensfeld** [comment]
Works like a charm. Closing. Thank you :pray:
